version: "3.7"

services:
  nginx:
    container_name: nginx
    depends_on:
      - api
      - frontend
      - mysql
    build:
      context: ./nginx
    networks:
      - internal
    volumes:
      - ./nginx/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/html
    ports:
      - 80:80
      - 443:443

  api:
    container_name: api
    build:
      context: ./api
      target: dev-stage
      #target: production-stage
    depends_on:
      - mysql
    networks:
      - internal
    ports:
      - 3000:3000
    volumes:
      - ./api:/srv

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: production-stage
      args:
        NODE_ENV: production
        BASE_URL: /frontend/
    depends_on:
      - mysql
    networks:
      - internal

  mysql:
    container_name: mysql
    image: mysql:8
    networks:
      - internal
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boilerplate 

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    networks:
      - internal
    ports: 
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

networks:
  internal:
    driver: bridge

volumes:
  mysql_data:
