version: "3.7"

services:
  nginx:
    container_name: nginx
    depends_on:
      - api
      - frontend
      - mysql
    build:
      context: ./nginx
    networks:
      - internal
    volumes:
      - ./nginx/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/html
    ports:
      - 80:80

  api:
    container_name: api
    build:
      context: ./api
      # target: dev-stage
      target: production-stage
    depends_on:
      - mysql
    networks:
      - internal
    # ports:
    #   - 3000:3000
    volumes:
      - ./api:/srv
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=boilerplate
      - DB_CONNECTION_LIMIT=10
      - DB_DEBUG=true
      - JWT_SECRET_KEY=aaGhu2foo7sheithePhai4Aef
      - JWT_EXPIRES_IN=1w
      - BCRYPT_SALTING_ROUND=10
      - API_URL=http://localhost/api
      - BACKEND_URL=http://localhost/backend
      - FRONTEND_URL=http://localhost/frontend
      - EMAIL_FROM_ADDRESS=support@boilerplate.local
      - EMAIL_FROM_NAME=Support
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_SECURE=false
      - SMTP_AUTH_USER=
      - SMTP_AUTH_PASS=
      - SMTP_DEBUG=true
      - SMTP_LOGGER=true
      - TZ=Australia/Melbourne

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: production-stage
      args:
        NODE_ENV: production
        BASE_URL: /frontend/        
    depends_on:
      - mysql
    networks:
      - internal
    environment:
      - API_URL=http://localhost/api

  backend:
    container_name: backend
    build:
      context: ./backend
      target: production-stage
      args:
        NODE_ENV: production
        BASE_URL: /backend/
    depends_on:
      - mysql
    networks:
      - internal
    environment:
      - API_URL=http://localhost/api

  mysql:
    container_name: mysql
    build:
      context: ./mysql
    networks:
      - internal
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boilerplate 
      TZ: Australia/Melbourne

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    networks:
      - internal
    # ports: 
    #   - 1025:1025 # smtp server
    #   - 8025:8025 # web ui

networks:
  internal:
    driver: bridge

volumes:
  mysql_data:
