on: 
  push:
    branches:
      # - master
      - apply-actions

jobs:
  build-dev:
    name: Build dev environment
    runs-on: ubuntu-latest
    env:
      REGISTRY_DOMAIN: ${{ secrets.REGISTRY_DOMAIN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: checkout source code
        uses: actions/checkout@master
      - name: docker hub login
        uses: actions/docker/login@master
      - name: build api image
        uses: actions/docker/cli@master
        with: 
          args: build ./api --target dev-stage -t $REGISTRY_DOMAIN/chrisleekr/nodejs-vuejs-mysql-boilerplate:api-dev
      - name: push api dev image
        uses: actions/docker/cli@master
        with: 
          args:  push $REGISTRY_DOMAIN/chrisleekr/nodejs-vuejs-mysql-boilerplate:api-dev