on: 
  push:
    branches:
      # - master
      - apply-actions

jobs:
  build-dev:
    name: Build dev environment
    runs-on: ubuntu-latest
    env:
      REGISTRY_DOMAIN: ${{ secrets.REGISTRY_DOMAIN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: docker hub login
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $REGISTRY_DOMAIN
      - name: Build api dev image
        run: |
          cd api
          docker build . --target dev-stage -t $REGISTRY_DOMAIN/chrisleekr/nodejs-vuejs-mysql-boilerplate:api-dev
          docker push $REGISTRY_DOMAIN/chrisleekr/nodejs-vuejs-mysql-boilerplate:api-dev
      - name: Build backend dev image
        run: |
          cd backend
          docker build . --target build-stage --build-arg NODE_ENV=$NODE_ENV --build-arg BASE_URL=$BASE_URL -t $REGISTRY_DOMAIN/chrisleekr/nodejs-vuejs-mysql-boilerplate:backend-dev
          docker push $REGISTRY_DOMAIN/chrisleekr/nodejs-vuejs-mysql-boilerplate:backend-dev
      - name: Build frontend dev image
        run: |
          cd frontend
          docker build . --target build-stage --build-arg NODE_ENV=$NODE_ENV --build-arg BASE_URL=$BASE_URL -t $REGISTRY_DOMAIN/chrisleekr/nodejs-vuejs-mysql-boilerplate:frontend-dev
          docker push $REGISTRY_DOMAIN/chrisleekr/nodejs-vuejs-mysql-boilerplate:frontend-dev

  api:
    name: API
    runs-on: ubuntu-latest
    env:
      REGISTRY_DOMAIN: ${{ secrets.REGISTRY_DOMAIN }}
    container:
      image: $REGISTRY_DOMAIN/chrisleekr/nodejs-vuejs-mysql-boilerplate:api-dev
    steps:
      - name: Install npm
        run: |
          pwd
          ls -al
          npm install
          npm lint        
