on: 
  push:
    branches:
      # - master
      - apply-actions

jobs:
  build-dev:
    name: Build dev environment
    runs-on: ubuntu-latest
    env:
      REGISTRY_DOMAIN: ${{ secrets.REGISTRY_DOMAIN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: checkout source code
        uses: actions/checkout@master
      - name: docker hub login
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $REGISTRY_DOMAIN
      - name: build api image
        run: |
          ls -al 
          pwd
          cd api
          docker build ./api --target dev-stage -t $REGISTRY_DOMAIN/chrisleekr/nodejs-vuejs-mysql-boilerplate:api-dev
          docker push $REGISTRY_DOMAIN/chrisleekr/nodejs-vuejs-mysql-boilerplate:api-dev

  # lint:
  #   name: Lint projects
  #   runs-on: ubuntu-latest
  #   container:
  #     image